name: rena_zelda_bocchi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.13.20
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/3estrellas.riv
    - assets/images/FondoMenu.png
    - assets/images/FondoMenuChico.png
    - assets/sounds/
