name: rena_zelda_bocchi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.13.20
  audioplayers: ^6.4.0
  supabase_flutter: ^2.9.0
  sign_in_with_apple: ^7.0.1
  google_sign_in: ^6.3.0
  material_design_icons_flutter: ^7.0.7296
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: ChalkFont
      fonts:
        - asset: assets/fonts/Schoolbell/Schoolbell-Regular.ttf  # 2 espacios de indentación

  assets:
    - assets/images/
    - assets/animations/3estrellas.riv
    - assets/images/FondoMenu.png
    - assets/images/FondoMenuChico.png
    - assets/sounds/